language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

services:
  - docker

script:
  - mkdir -vp _build
  - cd _build
  - autoreconf -ivf ..
  - ../configure
  - make clean all check distcheck install
